name: toc_prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas=2.2.3
  - numpy=2.1.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - matplotlib=3.10.1
  - seaborn=0.13.2
  - xgboost=2.1.4
  - pip:
    - bayesian-optimization==1.5.1 